Class Terminology.Production.Msg.FhirDesignation Extends %SerialObject
{

Property Language As %String;

Property Use As %String;

Property Value As %String;

Storage Default
{
<Data name="FhirDesignationState">
<Value name="1">
<Value>Language</Value>
</Value>
<Value name="2">
<Value>Use</Value>
</Value>
<Value name="3">
<Value>Value</Value>
</Value>
</Data>
<State>FhirDesignationState</State>
<StreamLocation>^Terminolog9AF9.FhirDesigna14ABS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
