Class Terminology.Production.Msg.LoincGetGroupsResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.GroupResult;

Storage Default
{
<Data name="LoincGetGroupsResponseDefaultData">
<Subscript>"LoincGetGroupsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincGetGroupsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
