Class Terminology.Production.Msg.LoincGetGroupMembersResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.GroupMemberResult;

Storage Default
{
<Data name="LoincGetGroupMembersResponseDefaultData">
<Subscript>"LoincGetGroupMembersResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincGetGroupMembersResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
