Class Terminology.Production.Msg.LoincGetAncestorsResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.ClosureResult;

Storage Default
{
<Data name="LoincGetAncestorsResponseDefaultData">
<Subscript>"LoincGetAncestorsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincGetAncestorsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
