Class Terminology.Production.Msg.LoincGetDisplaysResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.DisplayResult;

Storage Default
{
<Data name="LoincGetDisplaysResponseDefaultData">
<Subscript>"LoincGetDisplaysResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincGetDisplaysResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
