Class Terminology.Production.Msg.LoincValidateCodeResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.ValidateCodeResult;

Storage Default
{
<Data name="LoincValidateCodeResponseDefaultData">
<Subscript>"LoincValidateCodeResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincValidateCodeResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
