Class Terminology.Production.Msg.LoincGetDescendantsResponse Extends Ens.Response
{

Property Payload As Terminology.Loinc.DTO.ClosureResult;

Storage Default
{
<Data name="LoincGetDescendantsResponseDefaultData">
<Subscript>"LoincGetDescendantsResponse"</Subscript>
<Value name="1">
<Value>Payload</Value>
</Value>
</Data>
<DefaultData>LoincGetDescendantsResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
